const fallbackImage = 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=600&auto=format&fit=crop';

export const products = [
  {
    id: 'moon-glow',
    name: 'Moon Glow Polish',
    price: 899,
    image: '/moon_glow_polish_1777837345593.png',
    shortDesc: 'A soft, illuminating polish for an ethereal glow.',
    description: 'Experience the soft, feminine touch of the Moon Glow Polish. Designed to gently exfoliate while leaving a sensual, subtle shimmer on your skin. Perfect for an evening routine.',
    benefits: ['Subtle glow', 'Gentle exfoliation', 'Deeply nourishing'],
    ingredients: 'Sugar crystals, Jojoba oil, Pearl powder, Vanilla extract.',
    howToUse: 'Massage gently onto damp skin in circular motions. Rinse thoroughly and pat dry.',
  },
  {
    id: 'rose-cloud',
    name: 'Rose Cloud Polish',
    price: 899,
    image: '/rose_cloud_polish_1777836603661.png',
    shortDesc: 'Delicate blush pink polish infused with real rose petals.',
    description: 'Wrap yourself in the luxurious scent of fresh roses. This creamy blush pink scrub buffs away dullness while deeply hydrating the skin, leaving it petal-soft.',
    benefits: ['Hydrating', 'Softening', 'Sensory aromatherapy'],
    ingredients: 'Organic cane sugar, Sweet almond oil, Crushed rose petals, Rose essential oil.',
    howToUse: 'Apply to wet skin, gently scrub, and rinse with warm water.',
  },
  {
    id: 'coffee-velvet',
    name: 'Coffee Velvet Scrub',
    price: 599,
    image: '/coffee_velvet_scrub_1777836588363.png',
    shortDesc: 'Rich, aromatic coffee scrub for smooth, velvet skin.',
    description: 'Awaken your senses with the rich aroma of roasted coffee. This scrub is formulated to target cellulite and smooth the skin\'s texture, revealing a velvety finish.',
    benefits: ['Improves circulation', 'Firms skin', 'Exfoliates deeply'],
    ingredients: 'Ground robusta coffee, Coconut oil, Brown sugar, Vitamin E.',
    howToUse: 'Focus on areas needing extra attention. Scrub in circular motions for 2-3 minutes before rinsing.',
  },
  {
    id: 'golden-rio',
    name: 'Golden Rio',
    price: 1299,
    image: '/golden_rio_scrub_1777836620027.png',
    shortDesc: 'Premium golden scrub for a sun-kissed, luxurious feel.',
    description: 'Our most luxurious offering. Golden Rio transports you to a sun-drenched beach with its warm, glowing formula. Infused with 24k gold flakes and exotic oils.',
    benefits: ['Radiant glow', 'Intense moisture', 'Anti-aging properties'],
    ingredients: 'Dead sea salt, Argan oil, 24k Gold mica, Macadamia nut oil.',
    howToUse: 'Use 1-2 times a week for a luxurious, glowing finish.',
  },
  {
    id: 'floral-luxury',
    name: 'Floral Luxury Polish',
    price: 1499,
    image: '/floral_luxury_polish_1777837362238.png',
    shortDesc: 'An exquisite blend of exotic flowers for the ultimate self-care.',
    description: 'A premium, aesthetic experience. This polish is a sensory journey through a vintage French garden, designed to elevate your self-care routine to an art form.',
    benefits: ['Sensory experience', 'Silky smooth finish', 'Calms the mind'],
    ingredients: 'Fine sugar, Shea butter, Jasmine extract, Lavender oil.',
    howToUse: 'Take a generous scoop and gently massage onto damp skin. Breathe in the floral notes and rinse.',
  }
];
